# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import token_pb2 as token__pb2


class TokenInfoServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTokenInfo = channel.unary_unary(
                '/TokenInfoService/GetTokenInfo',
                request_serializer=token__pb2.GetTokenInfoRequest.SerializeToString,
                response_deserializer=token__pb2.GetTokenInfoResponse.FromString,
                )


class TokenInfoServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTokenInfo(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TokenInfoServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTokenInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTokenInfo,
                    request_deserializer=token__pb2.GetTokenInfoRequest.FromString,
                    response_serializer=token__pb2.GetTokenInfoResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TokenInfoService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TokenInfoService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTokenInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TokenInfoService/GetTokenInfo',
            token__pb2.GetTokenInfoRequest.SerializeToString,
            token__pb2.GetTokenInfoResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
